pay:
  environment: local

spring:
  cloud:
    config:
      enabled: ${CONFIG_SERVER_ENABLED:false}
    vault:
      enabled: ${VAULT_ENABLED:false}

logging:
  level:
    org.springframework.web.reactive.function.server.RequestPredicates: TRACE
    org.springframework.web.reactive.result.method: DEBUG
    org.springframework.http.server.reactive: DEBUG
    reactor.netty.http.server: DEBUG
